import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { auth, signOut } from "@/auth"
import { redirect } from "next/navigation";
import "./globals.css";

const notoSans = Noto_Sans({ variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  if (!session) {
    return (
      redirect('/(auth)/login')
    )
  }
  return (
    <html lang="en" className={notoSans.variable}>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="h-10">
            <Avatar className="mt-1.5 ml-1.5">
              <AvatarImage src={session.user?.image ?? ""} />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
