import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import Link from "next/link";
import { auth } from "@/auth"
import { redirect } from "next/navigation";
import UserMenu from "@/components/user-menu";
import Image from "next/image";
const notoSans = Noto_Sans({ variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  if (!session) {
    return redirect('/login')
  }

  return (
    <html lang="en" className={notoSans.variable}>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className=" flex justify-between bg-primary">
            <Link href="/">
              <div className="p-3">
                <Image src="/logo.png" alt="logo" width={100} height={20} />
              </div>
            </Link>
            <div>
              <UserMenu imageUrl={session.user?.image ?? ""} />
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
