import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { auth } from "@/auth"
import { redirect } from "next/navigation";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu";
import UserMenu from "@/components/user-menu";
const notoSans = Noto_Sans({ variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  if (!session) {
    return redirect('/login')
  }

  return (
    <html lang="en" className={notoSans.variable}>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="h-10 flex justify-between bg-primary">
            <div className="p-3">
              キメ旅っ!(まつばやしがロゴ作成した後にここに画像はいるよ)
            </div>
            <div>
              <UserMenu imageUrl={session.user?.image ?? ""} />
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
